services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: mkdir -p /data/public && echo "Public folder created" && rsync -a ./public/ /data/public/ && npm start
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars: []  # Burayı boş bırakabilirsiniz, .env dosyası kullanılacak
